export const ERROR_CODES = {
    AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",
    NOT_FOUND: "NOT_FOUND",
    CONFLICT: "CONFLICT",
    DUPLICATE: "DUPLICATE",
    BAD_REQUEST: "BAD_REQUEST",
    BUSINESS_ERROR: "BUSINESS_ERROR",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    INVALID_TOKEN: "INVALID_TOKEN",
} as const;

export const HTTP_STATUS = {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    INTERNAL_SERVER_ERROR: 500,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export type HttpStatus = (typeof HTTP_STATUS)[keyof typeof HTTP_STATUS];
